version: '3.8'
name: D-and-D-HelpDesk
services:
    php-apache-environment:
        container_name: PHP-Server
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - .:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: Database
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: guest
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"
    phpmyadmin:
        container_name: myAdminPanel
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db